// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var Point, canvas, center, ctx, cycle, draw, height, radius, update, width;
    canvas = document.getElementById('canvas');
    ctx = canvas.getContext('2d');
    width = $('#canvas').width();
    height = $('#canvas').height();
    radius = width / 2;
    center = {
      x: width / 2,
      y: height / 2
    };
    ctx.drawPoint = function(x, y, in_the_circle, radius) {
      if (radius == null) {
        radius = 2;
      }
      this.beginPath();
      if (in_the_circle) {
        this.fillStyle = 'rgba(192, 80, 77, 0.7)';
      } else {
        this.fillStyle = 'rgba(155, 187, 89, 0.7)';
      }
      this.arc(x, y, radius, 0, Math.PI * 2, false);
      return this.fill();
    };
    ctx.drawLine = function(a, b) {
      this.beginPath();
      this.moveTo(a.x, a.y);
      this.lineTo(b.x, b.y);
      return this.stroke();
    };
    Point = (function() {
      function Point(x, y) {
        this.x = x != null ? x : 0;
        this.y = y != null ? y : 0;
      }

      return Point;

    })();
    update = function() {
      return ctx.clearRect(0, 0, width, height);
    };
    draw = function() {};
    cycle = function() {
      update();
      draw();
      return setTimeout(cycle, 10);
    };
    return cycle();
  });

}).call(this);
